<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8281" started-at="2019-10-13T20:23:32 IST" finished-at="2019-10-13T20:23:40 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8281" started-at="2019-10-13T20:23:32 IST" finished-at="2019-10-13T20:23:40 IST">
      <class name="Management.testingMain">
        <test-method status="PASS" signature="Initialise()[pri:0, instance:Management.testingMain@1165b38]" name="Initialise" is-config="true" duration-ms="4162" started-at="2019-10-13T20:23:32 IST" finished-at="2019-10-13T20:23:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initialise -->
        <test-method status="FAIL" signature="initbrowser(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Management.testingMain@1165b38]" name="initbrowser" duration-ms="3746" started-at="2019-10-13T20:23:36 IST" data-provider="innerValue" finished-at="2019-10-13T20:23:40 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.qaclickacademy.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Jatashankar989@gmailcom]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Jaibabaji]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [FEATURED COURSES1] but found [FEATURED COURSES]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [FEATURED COURSES1] but found [FEATURED COURSES]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at Management.testingMain.initbrowser(testingMain.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initbrowser -->
        <test-method status="PASS" signature="close()[pri:0, instance:Management.testingMain@1165b38]" name="close" is-config="true" duration-ms="302" started-at="2019-10-13T20:23:40 IST" finished-at="2019-10-13T20:23:40 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Management.testingMain -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
